version: '2'
services:
  fpm:
    image: angelxmoreno/php7-fpm-alpine-dev-pgsql
    build:
      context: ./docker
      dockerfile: DockerfileFpm
    links:
    - mysql-test
    volumes:
    - '.:/var/www/html'
    - './docker/php.ini:/usr/local/etc/php/php.ini:ro'
  web:
    ports:
    - '8721:80'
    volumes:
    - './docker/site.conf:/etc/nginx/conf.d/_site.conf:ro'
  redis:
    ports:
    - '8723:6379'
    volumes:
    - './docker/data/redis/:/data'
  es:
    ports:
    - '8724:9200'
    - '8725:9300'
    volumes:
    - './docker/data/es/:/usr/share/elasticsearch/data'
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=random-address
    - MYSQL_USER=random-address
    - MYSQL_PASSWORD=random-address
    - MYSQL_DATABASE=random-address
    volumes:
    - './docker/data/mysql/:/var/lib/mysql'
    ports:
    - '8722:3306'
  mysql-test:
    container_name: random-address-mysql-test
    image: 'mariadb:10.1'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
    - MYSQL_ROOT_PASSWORD=random-address-test
    - MYSQL_USER=random-address-test
    - MYSQL_PASSWORD=random-address-test
    - MYSQL_DATABASE=random-address-test
    volumes:
    - './docker/data/mysql-test/:/var/lib/mysql'
    ports:
    - '8922:3306'
