version: '2'
services:
  fpm:
    container_name: random-address-fpm
    image: angelxmoreno/php7-fpm-alpine-dev-pgsql
    build:
      context: ./docker
      dockerfile: DockerfileFpm
    links:
    - redis
    - es
    - mysql
  web:
    container_name: random-address-nginx
    image: 'nginx:1.13-alpine'
    links:
    - fpm
    volumes:
    - './docker/site.conf:/etc/nginx/conf.d/_site.conf:ro'
    volumes_from:
    - fpm
  redis:
    container_name: random-address-redis
    image: 'redis:4.0-alpine'
    command: 'redis-server --appendonly yes'
  es:
    container_name: random-address-es
    image: 'elasticsearch:5-alpine'
  mysql:
    container_name: random-address-mysql
    image: 'mariadb:10.1'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
    - MYSQL_ROOT_PASSWORD=random-address
    - MYSQL_USER=random-address
    - MYSQL_PASSWORD=random-address
    - MYSQL_DATABASE=random-address
